name: "Ruff Check Result to PR Comment"

description: "Auto comment on PRs based on Ruff Check results"

branding:
  icon: code
  color: blue

inputs:
  analyze_log:
    description: "Path to the Ruff Check log file"
    required: true
  gh_token:
    required: true
    default: ${{ github.token }}
    description: "GitHub Token"
  verbose:
    description: "Enable verbose logging"
    required: false
    default: false

runs:
  using: composite
  steps:
    - uses: actions/checkout@v4
    # - name: Override octokit/core version and install deps
    #   shell: bash
    #   run: |
    #     npm install
    - uses: actions/setup-node@v4
      with:
        node-version: 20
    - run: |
        npm install @octokit/core
        ls -R node_modules
      shell: bash
    # - name: Install dependencies
    #   shell: bash
    #   run: ls
    # - name: Install dependencies
    #   working-directory: ./
    #   shell: bash
    #   run: npm ci
    - uses: actions/github-script@v7
      if: ${{ github.event_name == 'pull_request' }}
      env:
        ANALYZE_LOG: ${{ inputs.analyze_log }}
        GH_TOKEN: ${{ inputs.gh_token }}
        VERBOSE: ${{ inputs.verbose }}
      with:
        retries: 3
        script: |
          const analyzeLog = process.env.ANALYZE_LOG;
          const ghToken = process.env.GH_TOKEN;
          const verboseLogging = process.env.VERBOSE === 'true';

          const workingDir = process.env.GITHUB_WORKSPACE;
          const actionPath = process.env.GITHUB_ACTION_PATH;

          const path = require('path');
          const script = require(path.join(actionPath, 'index.js'));

          await script({ core, github, context, workingDir, analyzeLog, ghToken, verboseLogging })
