name: test

run-name: test

on: pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4

      - run: touch foo

      - uses: ./
        with:
          analyze_log: foo
